import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const distDir = join(import.meta.dir, '../../frontend/dist')
const outputFile = join(import.meta.dir, '../src/embedded-frontend.ts')

function walk(dir: string, base: string): string[] {
  const results: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      results.push(...walk(full, base))
    } else {
      results.push(full.slice(base.length).replace(/\\/g, '/'))
    }
  }
  return results
}

const files = walk(distDir, distDir)

const lines = ['// auto-generated by scripts/embed-frontend.ts — do not edit manually']
files.forEach((f, i) => {
  lines.push(`import _f${i} from "../../frontend/dist${f}" with { type: "file" }`)
})
lines.push('')
lines.push('export const embeddedFiles: Record<string, string> = {')
files.forEach((f, i) => {
  lines.push(`  ${JSON.stringify(f)}: _f${i},`)
})
lines.push('}')

writeFileSync(outputFile, lines.join('\n') + '\n')
console.log(`Embedded ${files.length} frontend files into src/embedded-frontend.ts`)
